### ISSUE TITLE
Fails to build on SciDB 19.11 setup

### ISSUE THREAD

**Issue by rvernica** [Paradigm4/shim#107]
I have a SciDB 19.11 setup on Ubuntu Xenial. Shim `v19.11` branch fails to build. 
```
# make
make -C src shim
...
"/usr/bin/gcc-4.9" -Wall -std=gnu99 -fopenmp -g -pedantic -DVERSION=\"19.11.0\" 
-DCOMMIT=\"\" -DUSE_WEBSOCKET -I. -DPROJECT_ROOT="\"/opt/scidb/19.11\"" 
-I"/opt/scidb/19.11/3rdparty/boost/include/" -I"/opt/scidb/19.11/include" 
-I"/opt/scidb/19.11/3rdparty/boost/include/boost/container" -DSCIDB_CLIENT  -fpic -g 
-o shim shim.c mongoose.c client.o sha512.o base64.o iniparser/libiniparser.a -lstdc++ 
-ldl -lz -pthread -L"/opt/scidb/19.11/3rdparty/boost/lib" -L"/opt/scidb/19.11/lib" -lscidbclient 
-lboost_system -Wl,--enable-new-dtags 
-Wl,-rpath,'$ORIGIN:$ORIGIN/../lib:$ORIGIN/../../:/opt/scidb/19.11/3rdparty/boost/lib:'
 -llog4cxx -lprotobuf
...
client.o: In function `scidbconnect':
/usr/local/src/shim-22ed205c5496441f0d83f97c273786c220a9eed9/src/client.cpp:69: 
undefined reference to 
`scidb::Credential::Credential(std::string const&, std::string const&)'
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'shim' failed
make[1]: *** [shim] Error 1
make[1]: Leaving directory '/usr/local/src/shim-22ed205c5496441f0d83f97c273786c220a9eed9/src'
Makefile:16: recipe for target 'shim' failed
make: *** [shim] Error 2
```
It looks like an `ld` error related to the `scidbclient` library. The library is present and `-lscidbclient` is provided as argument to `gcc`.
```
# nm -gD /opt/scidb/19.11/lib/libscidbclient.so | c++filt | grep Credential::Credential
00000000001161a0 T scidb::Credential::Credential(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
00000000001161e0 T scidb::Credential::Credential(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
00000000001161a0 T scidb::Credential::Credential(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
00000000001161e0 T scidb::Credential::Credential(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```
@JAKinchen do you have any idea of what could be the cause?

**Comment by rvernica** [comment]
Fixed in #108
